---
title: Apples and Oranges in Adolescent Depression Treatments.
subtitle: A conceptual and quantiative re-appraisal of control arms in clinical trials.
author:
  - name: Argyris Stringaris
    email: a.stringaris@ucl.ac.uk
    affiliations: 
        - id: ucl_1
          name: University College London
          department: Divisions of Psychiatry and Psychology and Language Science
          address: 1-19 Torrington Place
          city: London, UK
          state: 
          postal-code: WC1E 7HB
          country: United Kingdom
    attributes:
        corresponding: true
    note: 
  - name: Charlotte Burman
    email: c.burman@ucl.ac.uk
    affiliations:
        - ref: ucl_1
    note:
  - name: Dayna Bhudia
    email: d.bhudia@ucl.ac.uk
    affiliations:
        - ref: ucl_1
    note:
  - name: Carmen Moreno
    email: cmoreno@hggm.es
    affiliations:
        - id: HGM
          name: Hospital Gregorio Marañón
          department: Department of Psychiatry
          address: 46 C. del Dr. Esquerdo
          city: Madrid
          state:
          postal-code: 28007
          country: Spain
  - name: Samuele Cortese
    email: samuele.cortese@soton.ac.uk
    affiliations:
        - id: soton
          name: University of Southampton
          department: Centre for Innovation in Mental Health (CIMH), School of Psychology
          address: Highfield Campus, Building 44
          city: Southampton
          state:
          postal-code: SO17 1BJ
          country: United Kingdom
  - name: Georgina Krebs
    email: g.krebs@ucl.ac.uk
    affiliations:
        - ref: ucl_1
    note: 
abstract: |
  To follow
keywords: 
  - depression
  - adolescents
  - antidepressants
  - psychotherapy
date: last-modified
bibliography: emotion_concepts_paper.bib
format: 
  elsevier-pdf:
    keep-tex: true
    journal:
      name: Journal Name
      formatting: preprint
      model: 3p
      cite-style: super
---

# Introduction

Depression is the leading cause of disability in adolescents and influential guidelines recommend that it be treated with either psychotherapy or anti-depressant medication or their combination. The evidence base for this recommendation typically derives from the appraisal of randomised controlled trials (RCTs) in which one modality (psychotherapy or anti-depressants) are compared against a control condition. In this paper we: a) test the hypothesis that medication control arms are more efficacious than psychotherapy control arms and that this undermines the validity of treatment comparisons and therefore of existing guidelines about depression treatment; b) explore how variation in treatment control arms can itself be exploited to advance our thinking concerning the mechanisms of depression and its treatment.

Clinicians across medicine and other health professions are faced with choices betweent different treatment modalities for their patients, be it between surgical or medical (drug-based) treatments or, in the case of adolescent depression, between psychotherapy and antidepressant medication. To make informed choices, clinicians rely on the extant evidence, frequently summarised in the form of national guidelines or other treatment recommendations. Such a comparison is inherent in the internationally influential UK National Institute of Clinical Excellence (NICE) guidelines for adolescent depression which recommend that youth be first offered psychological therapy over medication for most presentations of depression. Such comparisons between the etwo treatment modalities are inherent in other recommendations, e.g. the practice parameter issued by the American Academy of Child and Adolescent Psychiatry or the Royal Australian and New Zealand College of Psychiatrists.

These recommendations are not based on head to head trials between modalities; only one head-to-head trial exists in adolescent depression Instead, they rely on the comparison of the results of randomised controlled trials (RCTs) of each modality against RCTs of the other. In other words, it rests on a comparison of comparisons.

In the case of antidepressant studies, the control is the placebo pill (standard also in the rest of medicine), whilst controls for psychotherapy studies can vary substantially from waiting list to treatment as usual to an attention control, such as psychoeducation. Stated in simple formal terms, the comparison relies on testing this equality,

$$Effect_{Med} = Effect_{Psy}$$ {#eq-1}

where *Effect* denotes the effect on depression that either medication (*Med* ) or psychotherapy (*Psy*) have. Yet for this indirect comparison to be valid, some basic assumptions need to hold. The most important of these is the *all-else-being-equal,* or more technically *ceteris paribus,* assumption with regards to trial design. By necessity, therefore, the control conditions for each antidepressant and psychotherapy trials must be equal for inferences to be valid. We call this the *equality of controls* assumption.

The importance of this assumption can be easily intuited by expanding equation 1 to include the comparisons on which each side of that equation rests:

$$Effect_{MedActive} - Effect_{MedControls} = Effect_{PsyActive} - Effect_{PsyControls}$$ {#eq-2}

where MedActive and PsyActive are the active arms of antidepressant and psychotherapy trials, respectively, and MedControls and PsyControls the respective control arms. The assumption here has to be that the controls are equal, that is, $$ Effect_{MedControls} = Effect_{PsyControls}$$ A few simple examples help illustrate why this assumption is important Let the two modalities of treatment be medication and surgery, and let there be a trial for each modality. In the medication trial 80% of participants respond to the antihypertensive and only 40% to placebo; in the surgery trial, 40% of people respond to surgery and 0% to sham. If one relied on Equation 1 to compare the treatments they would arrive at the absurd conclusion that the two treatments are equal and recommend to a patient that it does not really matter which one they choose. Playing around with numbers in which no equality of the respective control arms is required, leads to other risible conclusions. Yet, a focus on the equality of controls is surprisingly absent.

The importance of testing the equality of controls assumption for patients and the public can be vast because treatment guidelines, clinician's advice to patients, and patients' informed choices are all affected by the validity of treatment comparisons. Similarly, the rational allocation of public funds towards treatment modalities rests on valid comparisons between them.

Beyond its immediate clinical importance, understanding the nature of controls in clinical trials of depression is key for reasons of causal inference and mechanistic understanding of treatment. Adolescent depression is notable for a relatively high placebo effect: the proportion of adolescents responding to placebo is higher in depression than in anxiety, and it is higher for adolescent vs adult depression. The reasons for these differences remain unclear and are typically treated as nuisance effects to be minimised by using trial designs such as a placebo lead in period. However, an alternative view is that placebo effects, or more generally, variability in the response to control arms may be informative about mechanisms of improvement. If, for example, the antidepressant effect of placebo is stronger than that of equivalent control arms in psychotherapy, then we ought to ask about the possible explanations of such differences and consider whether they can be exploited for improving treatment delivery, as previously suggested.

In this paper, we have two aims: first, test whether the equality of controls assumption of adolescent depression treatment holds, and therefore scrutinise the validity of current recommendations concerning choice between treatment modalities; second,we explore variabiliity in trial control arms across and within the two treatment modalities and examine how they relate to anti-depressant effects.

Our main hypothesis is that the within group effect of psychotherapy controls is substantially weaker than that of the placebo pill and we will test this in random effects meta-regression. We will also use series of sensitivity analyses concerning restricting to specific psychotherapy control groups ( e.g. exclude waitlist controls or include only controls to cognitive and behavioural therapy (CBT)) or medication control groups (e.g. trials for the FDA-approved fluoxetine and escitalopram). We also conduct sensitivity analyses in the form of simulations, to ensure that results are robust to estimations of the standard error of the change scores.

We then go on to examine the control arms of psychological treatments in both a qualitative/descriptive way (e.g. the content of attention control) and by quantifying characteristics such as session frequency, duration of delivery. We then explore how these characteristics relate to the magnitude of within group change.

@stringarisDevelopmentalPathwaysChildhood2014

# Results

The data for the studies included in this metanalysis are summarised in Supplementary Table 1 and are also available as a csv dataframe on \[<https://github.com/transatlantic-comppsych/apples_oranges>\].

```{r, warning=FALSE, message = FALSE, echo=FALSE}
library(tidyverse)
df_long_for_metan <- read.csv("~/apples_and_oranges/df_long_for_metan")


# describe studies
n_unique_studies <- length(unique(df_long_for_metan$new_study_id))

  

df_count_studies <- df_long_for_metan %>% 
  group_by(psy_or_med, arm_effect_size) %>% 
  count(is.na(cohens_d))


df_count_studies <-rename(df_count_studies, is_missing = `is.na(cohens_d)`)

df_count_studies <-
  df_count_studies %>% 
  mutate(condition = case_when(psy_or_med == 0 & arm_effect_size == "cohens_d_active" ~ "medication_active",
                             psy_or_med == 0 & arm_effect_size == "cohens_d_control" ~ "medication_control",
                             psy_or_med == 1 & arm_effect_size == "cohens_d_active" ~ "psychotherapy_active",
                             psy_or_med == 1 & arm_effect_size == "cohens_d_control" ~ "psychotherapy_control")
  )

```

In total, there were `r length(unique(df_long_for_metan$new_study_id))` studies of which `r df_count_studies[df_count_studies$condition == "medication_active"& df_count_studies$is_missing == FALSE,]$n` belonged to active and `r df_count_studies[df_count_studies$condition == "medication_control"& df_count_studies$is_missing == FALSE,]$n` to control arms of antidepressant trials; there were also `r df_count_studies[df_count_studies$condition == "psychotherapy_active"& df_count_studies$is_missing == FALSE,]$n` psychotherapy active and `r df_count_studies[df_count_studies$condition == "psychotherapy_control"& df_count_studies$is_missing == FALSE,]$n` trials. Note that active and control arms do not exactly match because some studies used more than one control or active arm. There were also missing data on `r df_count_studies[df_count_studies$condition == "medication_active"& df_count_studies$is_missing == TRUE,]$n`, `r df_count_studies[df_count_studies$condition == "medication_control"& df_count_studies$is_missing == TRUE,]$n`, `r df_count_studies[df_count_studies$condition == "psychotherapy_active"& df_count_studies$is_missing == TRUE,]$n`, and `r df_count_studies[df_count_studies$condition == "psychotherapy_control"& df_count_studies$is_missing == TRUE,]$n` trial arms where data were missing for medication active, mediaction contrl, psychotherapy active, and psychotherapy control respectively. 

In order to conduct a met








