<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Stringaris et al">

<title>Fundamental Problems with the Evidence Base of Adolescent Depression Treatments</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Untitled_files/libs/clipboard/clipboard.min.js"></script>
<script src="Untitled_files/libs/quarto-html/quarto.js"></script>
<script src="Untitled_files/libs/quarto-html/popper.min.js"></script>
<script src="Untitled_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Untitled_files/libs/quarto-html/anchor.min.js"></script>
<link href="Untitled_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Untitled_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Untitled_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Untitled_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Untitled_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="Untitled_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="Untitled_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fundamental Problems with the Evidence Base of Adolescent Depression Treatments</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Stringaris et al </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
<hr>
<hr>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>There are two principal treatment modalities for adolescent depression: psychotherapy, medication, or both. Where does one turn to find the evidence that will inform their treatment options? This question is relevant for patients and their carers, for clinicians and for policy makers when they plan services. However, the question is particularly difficult to answer for adolescent depression, where there are limited data from head-to-head trials of medication and psychotherapy, and where recommendations must therefore be derived from indirect comparisons of treatment efficacy.</p>
<p>Guidelines, such as the ones that the internationally influential UK National Institute of Clinical Excellence (NICE) have produced for adolescent depression, are a principal source of such information. NICE recommend that youth be first offered psychological therapy (specifically cognitive behaviour therapy and interpersonal therapy) over medication for most presentations of depression. This conclusion is in keeping with two sources of evidence. On the one hand, medication meta-analyses that cast doubt on the efficacy of most antidepressants, with the exception of fluoxetine (ref); and on the other hand, psychotherapy meta-analyses that conclude psychotherapy to be effective for adolescent depression (ref). However, such conclusions seem at odds with those of a recent network meta-analysis (ref), an established method of comparing treatments with each other using both direct (head-to-head) and indirect (indirectly treatment A with treatment C, via studies that directly compare treatments A with B and B with C) evidence. Indeed, the network meta-analysis concluded that only fluoxetine alone and fluoxetine administered together with CBT were significantly more effective than pill placebo or psychological controls. Given this confusing evidence base, how should patients, carers, clinicians and policy makers make decisions on treatment options for adolescent depression?</p>
<p>In this paper, we examine whether the existing evidence base for adolescent depression treatment can offer valid answers to such questions. Below, we provide a conceptual framework for answering such questions and state our hypotheses that we will test using data from existing trials. Two points are relevant to indirect comparisons of treatment modalities with each other.</p>
<p>First, whether the participants of trials in one modality are comparable to those in another modality. Second, whether key conditions of the trial, such as the effects of control conditions or the number of sites involved in a trial, are comparable.</p>
<p>Starting with the first point, to be able to compare between different trials one must assume that these trials sample from the same population. If they do not, then the validity of any comparisons, including those conducted through network metanalysis (which rests on the principal of transitivity) are questionable.</p>
<p>Indeed, comparing outcomes (Y) between psychotherapy and medication trials requires us to contrast what is called the sample average treatment effect <span class="math inline">\(\tau\)</span> of each, defined in the following way:</p>
<p><span class="math display">\[
\tau_{psy} =  E(Y_{1} - Y_{0} \,|\, S, psy)
\]</span> <span class="math display">\[
\tau_{med} =  E(Y_{1} - Y_{0} \,|\, S, med)\
\]</span></p>
<p>where the operator E denotes the expectation over the differences in outcomes between those who received the intervention (T = 1) and those who received the control condition (T = 0), for each sample, <span class="math inline">\(S\)</span>, where psy and med stand for psychotherapy and medication respectively.</p>
<p>Obviously, this comparison rests on the assumption that trials in both modalities sample from the same population, <span class="math inline">\(P\)</span>, of patients. Formally, this can be expressed as follows:</p>
<p><span class="math display">\[E(Y_{1} \,|\, \text{S, psy}) = E(Y_{1} \,|\, P, \text{psy})\]</span></p>
<p><span class="math display">\[E(Y_{1} \,|\, \text{S, med}) = E(Y_{1} \,|\, P, \text{med})\]</span></p>
<p>signifying that the effect found in the population would be expected to be found in the same population for each treatment.</p>
<p>This assumption may be hard to meet. Clinical experience and empirical evidence (ref: (<a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4156137/" class="uri">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4156137/</a>, <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7669695/#:~:text=Adolescents%20also%20may%20be%20more,medications%2C%20and%20fewer%20anxiety%20symptoms." class="uri">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7669695/#:~:text=Adolescents%20also%20may%20be%20more,medications%2C%20and%20fewer%20anxiety%20symptoms.</a> , <a href="https://pubmed.ncbi.nlm.nih.gov/16502131/" class="uri">https://pubmed.ncbi.nlm.nih.gov/16502131/</a>) indicate that patients and parents often have preferences between psychotherapy and medication, meaning that there is likely to be a self- %&gt;% ion bias with respect to who participates in psychotherapy versus medication trials. Moreover, these treatment preferences correlate with clinically-relevant characteristics of the participants, including severity, gender and comorbidity. Some of these characteristics, particularly baseline severity, may moderate treatment response (ref) and therefore, if they differ across psychotherapy and medication trials, they may confound comparisons.</p>
<p>Here we will compare between four key sample characteristics, namely baseline severity in the outcome, number of sites, gender and age in each sample.</p>
<p>In terms of the second point, differences in trial design may impact outcomes in a differential way between antidepressant and psychotherapy trials. Perhaps the most obvious way in which this happens is the fact that participants in psychotherapy trials are unblinded in terms of treatment allocation; by contrast, in new antidepressant trials, patients (and raters) were found to be unlikely to be able to judge treatment allocation (cite: Assessment of blinding in randomized controlled trials of antidepressants for depressive disorders 2000−2020: A systematic review and meta-analysis, Lancet). This creates differential expectations between medication and psychotherapy trials. Importantly, the placebo control has been developed in order to match as closely as possible the intervention condition, so as to minimise differences in expectancy between conditions. By contrast, psychotherapy control arms vary across waitlist controls, treatment as usual and active controls. These differences in expectation essentially favour the psychotherapy active condition and disadvantage the psychotherapy control (thus potentially the difference between them), because participants in the active condition could be content for receiving the “cutting edge treatment” whilst those in the control will be dissatisfied for having missed out on “proper treatment”. And this is important because expectancy is associated with treatment outcomes. This also poses problems when trying to infer indirect comparisons in network metanalyses where, for example, CBT is compared to placebo control and medication — given the likely differential expectation effects, comparisons to the unblinded psychotherapy controls may be biased.</p>
<p>Another difference in design that has potential implications for which patients are selected into the trial is the number of sites in a trial. Previous research has shown that in medication trials the number of sites is positively related to the magnitude of the placebo response. This phenomenon is hard to explain fully with the data available, but may be due to lower quality of phenotyping in such studies, with higher measurement (and therefore diagnostic classification) errors, leading to issues such as spontaneous remission or regression to the mean. In contrast to medication trials, psychotherapy trials typically involve one or fewer sites.</p>
<p>An inter-related issue concerns the nature of control interventions being used. Control conditions in trials are meant to generate counterfactual conditions (CITE RUBIN et al) to the intervention: what would have been the outcome in an individual had they not received the intervention. This implies that there is a latent distribution of values that represent that counterfactual condition which control arms in trials are meant to approximate. Those latent values of the counterfactual condition should, on average, not be different between psychotherapy and medication trials, provided that the samples are representative of the same underlying population (see Eqs 1&amp; 2). If the average response to placebo and psychotherapy controls differs systematically from each other, then this is either due to the fact that the trials sample from different populations or because the control conditions differ in their effects (e.g.&nbsp;because of how much they do or do not protect against expectancy effects).</p>
<p>Understanding the nature of controls for each treatment modality is important for a similar reason. Often, in the public domain, psychotherapy and medication are compared to each other on the basis of their respective effect sizes. However, as evident from Eqs 1 and 2, these effect sizes represent differences between the active intervention and the control condition (placebo or psychotherapy control). For these effect sizes to be comparable, placebo and psychotherapy controls ought to be the equal. Otherwise, misleading conclusions could be drawn, e.g.&nbsp;two effect sizes of 40% would be considered equal, even if one arose from a difference of 100% - 60% and another arose from a difference of 40% - 0%.</p>
<p>In this paper, we examine psychotherapy and medication trials in the following ways. First, we compare key baseline characteristics of medication vs psychotherapy trials, specifically the extent to which they are comparable in a) baseline severity; b) number of sites involved; c) gender composition and d) age. Second, we assess the mean efficacy of psychotherapy controls vs placebo. We recognise that both these sets of analyses pull data out of the randomised comparisons between treatment arms. However, we believe that this is justified for two reasons: a) because it is important to make transparent to all, particularly decision makers in healthcare, the raw data before these are entered into more complex modelling such as network metanalysis, as this allows them to form opinions about the quality and limitations of the input data; b) our aim here is not to make claims about the relative efficacy of each treatment arm, but rather establish whether the conditions for the possibility of comparisons are fulfilled. Thus, the comparisons between control conditions are not meant to lead to inferences about placebo being “more efficacious” than psychotherapy controls, but rather to make transparent the problem that they seem to derive from different distributions. Third, we examine the quality of psychotherapy controls as such, by scrutinising the extent to which they are matched to the active intervention in ways such as number or frequency of sessions, and therefore, whether they represent fair pairings from which to draw valid efficacy inferences.</p>
<p><span class="citation" data-cites="stringarisDevelopmentalPathwaysChildhood2014">@stringarisDevelopmentalPathwaysChildhood2014</span></p>
</section>
<section id="method" class="level1">
<h1>Method</h1>
<section id="studies-included" class="level2">
<h2 class="anchored" data-anchor-id="studies-included">Studies included</h2>
<p>For this review, we primarily drew upon studies included in two recent meta-analyses. Please refer to these original meta-analyses for a detailed description of study selection criteria. Psychotherapy studies were drawn from Cuijpers’ (2023) systematic review and meta-analysis of randomised trials comparing psychotherapy for youth depression against control conditions. Cuijpers made available a full dataset of psychotherapy trials (via https://www.metapsy.org/), which we used for the current study. Whilst Cuijpers (2023) excluded those studies for which the primary outcome variable could not be calculated due to missing data, we included these studies and performed the imputations outlined below; hence we have more psychotherapy studies included in this review compared to Cuijpers’ (2023) meta-analysis. Whilst the online database is regularly updated, we chose to exclude studies published after the final date of Cuipers’ (2023) literature search.</p>
<p>Medication studies were drawn from Cipriani’s (2016) network meta-analysis examining the efficacy and tolerability of a range of antidepressants and placebo for major depressive disorder in young people. The study dataset was made available online though did not include means or standard deviations at baseline or post-test. We emailed the study authors requesting a full dataset with this data, though did not receive a reply, and hence conducted data extraction for medication studies. We excluded three studies because they did not include a control arm. We were unable to locate and therefore complete extraction for two papers. Many studies did not report complete data, and so we emailed all corresponding authors to request missing data, though did not receive any responses. We conducted a systematic search for medication studies published after the final search date of Cipriani’s (2016) review up to the final search date of Cuijpers’ (2023) review to ensure we analysed an equivalently up-to-date database of medication trials. We used the same search terms outlined in Cipriani (2016).</p>
</section>
<section id="statistical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="statistical-analysis">Statistical Analysis</h2>
<section id="trial-and-sample-characteristics" class="level3">
<h3 class="anchored" data-anchor-id="trial-and-sample-characteristics">Trial and sample characteristics</h3>
<p>We conducted a series of random effects meta-analyses and tested for subgroup differences between psychotherapy versus medication trials in sample characteristics including gender, age, and severity of depressive symptoms at baseline. Meta-analyses were implemented using R’s meta package.</p>
<p>In order to compare depression severity across different instruments, we performed a min-max normalisation to turn each study arm mean score at baseline into a percentage using the following formalism:</p>
<p><span class="math display">\[
\text{outcome}_{percent} = \frac{\bar{X} - \text{scale}_{min}}{\text{scale}_{max} - \text{scale}_{min}}
\]</span></p>
<p>where, <span class="math display">\[\bar{X}\]</span> is the mean score for each study arm on the primary outcome questionnaire, and <span class="math inline">\({scale}_{min}\)</span> and <span class="math inline">\({scale}_{max}\)</span> are the minimum and maximum possible values of the scale in question, respectively. The standard deviation is calculated thus:</p>
<p><span class="math display">\[
\text{SD}_{Xpercent} = \frac{\text{SD}_{X}}{\text{scale}_{max} - \text{scale}_{min}}
\]</span></p>
<p>where <span class="math inline">\(\text{SD}_{X}\)</span> is the original standard deviation of the mean at baseline.</p>
<p>We also conducted a t-test to compare mean number of trial sites between psychotherapy and medication trials.</p>
</section>
<section id="measures-of-effect" class="level3">
<h3 class="anchored" data-anchor-id="measures-of-effect">Measures of Effect</h3>
<p>As the measure of effect of each individual study, we used the within-group Standardised Mean Difference (SMD), which we defined following NOTE: Charlotte cite Lakens 2013 and in there Cummings 2012, as:</p>
<p><span class="math display">\[SMD_{change} = \frac{Mean_{t_{2}} - Mean_{t_{1}}}{\frac{SD_{t{2}} + SD_{t{1}}}2}\ \]</span></p>
<p>where, <span class="math inline">\(Mean_{t_{2}}\)</span> and <span class="math inline">\(Mean_{t_{1}}\)</span> refer to the means of the main outcome score at the end and beginning of the intervention respectively and <span class="math inline">\(SD_{t_{2}}\)</span> and <span class="math inline">\(SD_{t_{1}}\)</span> to the respective standard deviations. Where individual studies did not report all data required to calculate the SMD, we imputed missing data according to the methods summarised by X (citation), in the following order. If a study reported the standard error of the mean, the SD was obtained simply by multiplying the SE by the square root of the sample size. For conditions where the SD was missing at one time point, the baseline SD was substituted by the post-test SD, and vice versa. If the SD was not available at either time point, missing values were replaced by the mean of the SDs available for comparable cases (defined as same trial type (psy or med), same instrument, same timepoint (pre or post), and same arm (control or active)). Where there were missing means at either baseline or post-test, missing values were calculated using mean change scores, preferring the change scores reported in the paper itself, though where this was unavailable, using the change scores reported in the dataset from Cipriani’s meta-analysis (citation).</p>
<p>For the purposes of metanalysis, it is necessary to estimate a standard error of the SMD. This is calculated according to:</p>
<p><span class="math display">\[ SE_{SMD} = \sqrt{\frac{2(1 -r_{t_{1}t_{2}})}{n} + \frac{SMD^2}{2n}}\]</span></p>
<p>where <span class="math inline">\(n\)</span> refers to the study sample size and <span class="math inline">\(r_{t_{1}t_{2}}\)</span> refers to the correlation between the outcome score obtained at baseline and at the end point. This correlation is typically not reported in studies and is often imputed using previously reported correlations for the instruments used. However, this practice has given rise to concerns about misestimation. Whilst such misestimation is possible, there is no reason to expect that it would be systematic, i.e.&nbsp;bias estimation of the effects for the control group of medication compared to those of psychotherapy. Still, to alleviate such concerns we have used a simulations.</p>
<p>In particular, we simulated one thousand truncated distribution of standard errors with the following general characteristics:</p>
<p><span class="math display">\[r_{t_{1}t_{2}} \sim \mathcal{TN}(\mu, \sigma, a, b)\]</span></p>
<p>for which we chose the mean to be <span class="math inline">\(\mu = 0.65\)</span>, the standard deviation to be <span class="math inline">\(\ sigma = 0.2\)</span>, and the upper and lower bounds to be <span class="math inline">\(a = 0.45\)</span> and <span class="math inline">\(b = 0.9\)</span>, respectively. We then used these simulated datasets in the subsequent metanalyses.</p>
</section>
<section id="random-effects-metaregression" class="level3">
<h3 class="anchored" data-anchor-id="random-effects-metaregression">Random Effects Metaregression</h3>
<p>We estimated the pooled standardised mean difference for each arm by using a random effects metanalysis implemented in R’s metafor package. The main underlying assumption of random effects metanalysis is that each study’s true effect size <span class="math inline">\(\theta_{k}\)</span> is affected not only by sampling error <span class="math inline">\(\epsilon_{k}\)</span>, but also by <span class="math inline">\(\zeta\)</span> which represents heterogeneity between studies, allowing each study’s estimate to vary along a distribution of effects, and the distribution of true effect sizes termed <span class="math inline">\(\tau^2\)</span>. Therefore, we can estimate a two stage model with:</p>
<p><span class="math display">\[Y_i \sim \mathcal{N}(\theta_i, \sigma_i^2)
\]</span></p>
<p><span class="math display">\[\theta_i \sim \mathcal{N}(x_i\beta, \tau_i^2)
\]</span></p>
<p>where <span class="math inline">\(Y_i\)</span> is the estimated effect size for study i, has a normal distribution with <span class="math inline">\(\theta_i\)</span> as its true mean effect and sampling error <span class="math inline">\(\sigma^2\)</span>. Whereas <span class="math inline">\(\theta_i\)</span> is a study-specific instantiation of the distribution of effect sizes, with <span class="math inline">\(\tau^2\)</span> representing heterogeneity.</p>
<p>This then gives rise to:</p>
<p><span class="math display">\[Y_i = x_i\beta_i + u_i + \epsilon_i\]</span></p>
<p>where,</p>
<p><span class="math display">\[u_i \sim N(0, \tau^2) \]</span></p>
<p>describes the deviation of each study from the mean of the distribution, and,</p>
<p><span class="math display">\[\epsilon_i \sim N(0, \sigma^2)\]</span></p>
<p>describes the sampling error.</p>
<p>We can then specify the following model to obtain the means of each arm of the trials as follows:</p>
<p><span class="math display">\[ \begin{aligned}
    Υ_i &amp;=
    \begin{cases}
        0 &amp; MedControl:  b_0 + u_i + \epsilon_i\\
        1 &amp; MedActive:   b_0 + b_{1_{i}} +  u_i + \epsilon_i \\
        2 &amp; PsyActive:   b_0 + b_{2_{i}}  +  u_i + \epsilon_i \\
        3 &amp; PsyControl:  b_0 + b_{3_{i}}  +  u_i + \epsilon_i \\
    \end{cases}
\end{aligned}\]</span></p>
<p>where to obtain the mean of each level is the sum of <span class="math inline">\(b_0\)</span>, the intercept for the reference category of medication control, with the coefficient of each level, e.g.&nbsp;for level 3, <span class="math inline">\(b_{3_{i}}\)</span> the psychotherapy controls. The confidence intervals of the means are constructed in the standard way using the standard errors of the mean. Similarly, each coefficient represents the contrast between the reference category and each level, for an example and of main interest to us <span class="math inline">\(b_{3_{i}}\)</span> represents the contrast between psychotherapy and medication control arms. Inference on the contrasts is done as follows:</p>
<p><span class="math display">\[
z = \frac{\hat{\beta}}{\text{SE}(\hat{\beta})}
\]</span></p>
<p>We used maximum likelihood (ML) to estimate model and applied Hartung-Knapp adjustment to reduce the chance of false positives (NOTE: <strong>Charlotte</strong>cite Ioannides on this).</p>
<p>We present our main results as means of the estimates across simulated datasets, for example, the SMDs of each level of the dummy variable above are means across the simulations.</p>
</section>
<section id="sensitivity-analyses" class="level3">
<h3 class="anchored" data-anchor-id="sensitivity-analyses">Sensitivity Analyses</h3>
<p>We conducted a number of additional analyses to test for the robustness of our results.</p>
<p>First, for each of the the analyses comparing trial and sample characteristics at baseline, and control efficacy between study arms, we performed sensitivity analyses where we restricted the included studies in the following ways. First, we excluded studies which recruited participants with subclinical levels of depression. Second, we restricted the analyses to studies using CBT and the FDA-approved antidepressants fluoxetine and escitalopram. Third, we excluded studies that used waitlist as their control condition.</p>
<p>Further, we tested whether the simulated values for the standard error had a substantial influence on the estimation of the differences between the medication vs psychotherapy control condition. To inspect whether this is the case, we plotted the z-value of the difference between the two coefficients against the number of simulations. We make inference on the stability of the difference, by counting the proportion of times that the z-value is above the</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>critical value of z = 1.645 corresponding to an alpha = 0.05. </code></pre>
</div>
</div>
</section>
<section id="comparing-the-control-versus-active-arms-of-psychotherapy-trials" class="level3">
<h3 class="anchored" data-anchor-id="comparing-the-control-versus-active-arms-of-psychotherapy-trials">Comparing the control versus active arms of psychotherapy trials</h3>
<p>We ran t-tests to compare the active versus control arms of psychotherapy trials on key variables of interest regarding the nature and intensity of the interventions. We extracted data pertaining to the number, duration and intensity of sessions, and the total cumulative hours and period of the intervention. Where a range was provided, the maximum was encoded (e.g.&nbsp;if a paper reported that an intervention involved 8-10 sessions lasting 50-60 minutes, we encoded the number and duration of sessions as 10 and 60, respectively). If sessions varied in frequency across an intervention, we calculated an average by dividing total number of sessions by length of intervention period. Similarly, if the length of sessions varied across the course of the intervention, we calculated a weighted average. Phone call, web-chat and online sessions were encoded as sessions, however guided self-help components were not.</p>
</section>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="included-studies" class="level2">
<h2 class="anchored" data-anchor-id="included-studies">Included studies</h2>
<p>The data for the studies included in this metanalysis are summarised in Supplementary Table 1 and are also available as a csv dataframe on [<a href="https://github.com/transatlantic-comppsych/apples_oranges" class="uri">https://github.com/transatlantic-comppsych/apples_oranges</a>].</p>
<p>In total, there were 81 studies which included 28 active arms and 25 control arms of antidepressant trials; and 55 active arms and 52 control arms from psychotherapy trials. Note that the number of active and control arms does not exactly match because some studies feature more than one control or active arm. There were also missing data for 4, 4, 6, and 6 trial arms for medication active, medication control, psychotherapy active, and psychotherapy control conditions respectively, as the data needed to calculate the SMD was missing and could not be imputed by any of the methods outlined above.</p>
<p>Placebo was the control condition for all medication trials; the active arm ranged from serotonin reuptake inhibitors, such as 6 fluoxetine and 2 escitalopram, to tricylics, such as 2 nortriptyline. In psychological trials, the control arm included 14 WL controls, 25 care as usual and several other conditions such as 4 attention control conditions; the active arm included 43 CBT and 8 IPT amongst others. All included trials and the types of treatment controls can be found in Supplementary Table 1.</p>
</section>
<section id="sample-characteristics-at-baseline-in-medication-versus-psychotherapy-trials" class="level2">
<h2 class="anchored" data-anchor-id="sample-characteristics-at-baseline-in-medication-versus-psychotherapy-trials">Sample characteristics at baseline in medication versus psychotherapy trials</h2>
<p>Table 1 summarises the results from each of the meta-analyses examining sample characteristics at baseline. The summary statistics are provided for each subgroup (i.e.&nbsp;for medication and psychotherapy trials) and the p-value derives from the test for subgroup differences. Full results for each of the sensitivity analyses are included in the Supplementary Materials (Table X - Y).</p>
<section id="baseline-severity" class="level3">
<h3 class="anchored" data-anchor-id="baseline-severity">Baseline severity</h3>
<p>On average, severity of depressive symptoms at baseline was significantly higher in medication trials when compared to psychotherapy trials. The statistics provided in Table 1 are baseline depression scores transformed to reflect percentage of a scale range. To take an example, the CDRS gives a possible total score from 17 to 113 (i.e.&nbsp;range of 96). From Table 1, mean severity was 0.36 for psychotherapy studies and 0.42 for medication studies, which would translate to 51.56 (17 + 0.36 x 96) and 57.32 (17 + 0.42 x 96), respectively, as equivalent scores on the CDRS.</p>
<p>When taking only those studies where the active arm was either CBT, fluoxetine or escitalopram, there was a significant difference between psychotherapy and medication studies. This difference did not reach statistical significance when excluding psychotherapy studies that recruited samples with sub-clinical depression or when excluding studies that used wait list as their control. Please refer to Table S1 for these results.</p>
</section>
<section id="gender" class="level3">
<h3 class="anchored" data-anchor-id="gender">Gender</h3>
<p>As can be seen in Table 1, psychotherapy trials featured a significantly higher percentage of women when compared to medication trials. On average, samples were comprised of 60.9% (<em>SE</em> = 2.4) women across psychotherapy trials and 51.5% (<em>SE</em> = 2.9) women across medication trials. Excluding sub-clinical and waitlist control studies yielded very similar results. This difference in gender composition however did not reach statistical significance when only CBT, fluoxetine and escitalopram trials were included (see Table S2).</p>
</section>
<section id="age" class="level3">
<h3 class="anchored" data-anchor-id="age">Age</h3>
<p>As can be seen in Table 1, mean age was 14.24 (<em>SE</em> = 0.34) across psychotherapy trials and 13.6 (<em>SE</em> = 0.47) across medication trials, with no significant between group differences. There were no significant differences in mean age between modalities on further sensitivity analyses (see Table S3).</p>
<div class="cell">
<div class="cell-output-display">
<table class="lightable-material lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Sample characteristics at baseline across medication and psychotherapy studies</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Subgroup</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">K</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Mean</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">SE</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Lower CI</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Upper CI</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">T2</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">p-value<sup>1</sup></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">Severity</td>
<td style="text-align: left; font-weight: bold;"></td>
<td style="text-align: left; font-weight: bold;"></td>
<td style="text-align: left; font-weight: bold;"></td>
<td style="text-align: left; font-weight: bold;"></td>
<td style="text-align: left; font-weight: bold;"></td>
<td style="text-align: left; font-weight: bold;"></td>
<td style="text-align: left; font-weight: bold;">0.023</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Psychotherapy</td>
<td style="text-align: left;">47</td>
<td style="text-align: left;">0.36</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">0.32</td>
<td style="text-align: left;">0.4</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Medication</td>
<td style="text-align: left;">24</td>
<td style="text-align: left;">0.42</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">0.38</td>
<td style="text-align: left;">0.45</td>
<td style="text-align: left;">0.01</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-top: 1px solid black; border-right: 1px solid;">Percent Women</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;"></td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;"></td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;"></td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;"></td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;"></td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;"></td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">0.013</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Psychotherapy</td>
<td style="text-align: left;">46</td>
<td style="text-align: left;">60.9</td>
<td style="text-align: left;">2.38</td>
<td style="text-align: left;">56.11</td>
<td style="text-align: left;">65.69</td>
<td style="text-align: left;">260.19</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Medication</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">51.5</td>
<td style="text-align: left;">2.92</td>
<td style="text-align: left;">45.4</td>
<td style="text-align: left;">57.6</td>
<td style="text-align: left;">179.41</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-top: 1px solid black; border-right: 1px solid;">Age</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;"></td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;"></td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;"></td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;"></td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;"></td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;"></td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">0.271</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Psychotherapy</td>
<td style="text-align: left;">51</td>
<td style="text-align: left;">14.24</td>
<td style="text-align: left;">0.34</td>
<td style="text-align: left;">13.56</td>
<td style="text-align: left;">14.92</td>
<td style="text-align: left;">5.85</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Medication</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">13.6</td>
<td style="text-align: left;">0.47</td>
<td style="text-align: left;">12.61</td>
<td style="text-align: left;">14.58</td>
<td style="text-align: left;">4.68</td>
<td style="text-align: left;"></td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup>1</sup> Statistic derived from the test for subgroup differences in the relevant meta-analysis</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</section>
<section id="number-of-trial-sites" class="level3">
<h3 class="anchored" data-anchor-id="number-of-trial-sites">Number of trial sites</h3>
<p>There was a significant difference between the number of sites in medication versus psychotherapy trials, as can be seen in Tables 2 and 3. Average number of trial sites was significantly higher across medication studies ( <em>M</em> = 29.76, <em>SD</em> =18.52) compared to psychotherapy studies ( <em>M</em> =3.07, <em>SD</em> =3.16)(<em>t</em> (20.54) = 6.56, <em>p</em> =1.8898978^{-6}).</p>
<div class="cell">
<div class="cell-output-display">
<table class="lightable-material lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Results for t-test comparing number of sites between medication and psychotherapy studies</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">statistic</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">df</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">p_value</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">ci_lower</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">ci_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid;">t</td>
<td style="text-align: left;">6.56</td>
<td style="text-align: left;">20.54</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: left;">18.22</td>
<td style="text-align: left;">35.17</td>
</tr>
</tbody>
</table>


</div>
</div>
<section id="mean-efficacy-of-psychotherapy-versus-medication-control-conditions" class="level4">
<h4 class="anchored" data-anchor-id="mean-efficacy-of-psychotherapy-versus-medication-control-conditions">Mean efficacy of psychotherapy versus medication control conditions</h4>
<p>We applied metaregression to obtain the SMDs and confidence intervals of each of the four arms.</p>
<p>As can be seen in Figure 1, there were substantial differences between the four arms of the metanalysis with striking differences between the medication and the psychotherapy control arms. In particular, placebo had an SMD = -1.8 (95% CI: -2.03 to -1.56) whereas psychotherapy controls had an SMD = -0.51 (95% CI: -0.79 to -0.22 ) (see Table 4 below).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><embed src="plot_means_all.pdf" class="img-fluid"></p>
<figcaption class="figure-caption">Figure 1.</figcaption>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="lightable-material lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Summary statistics of the estimated SMDs</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">Condition</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">N</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">Coefficient</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">SE</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">Lower CI</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">Upper CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid;">Medication Control</td>
<td style="text-align: left;">28</td>
<td style="text-align: left;">-1.80</td>
<td style="text-align: left;">0.12</td>
<td style="text-align: left;">-2.03</td>
<td style="text-align: left;">-1.56</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid;">Medication Active</td>
<td style="text-align: left;">25</td>
<td style="text-align: left;">-2.02</td>
<td style="text-align: left;">0.16</td>
<td style="text-align: left;">-2.34</td>
<td style="text-align: left;">-1.70</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid;">Psychotherapy Control</td>
<td style="text-align: left;">55</td>
<td style="text-align: left;">-0.51</td>
<td style="text-align: left;">0.14</td>
<td style="text-align: left;">-0.79</td>
<td style="text-align: left;">-0.22</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid;">Psychotherapy Active</td>
<td style="text-align: left;">52</td>
<td style="text-align: left;">-1.16</td>
<td style="text-align: left;">0.15</td>
<td style="text-align: left;">-1.44</td>
<td style="text-align: left;">-0.87</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>In Table 5, we present the regression that tests our hypothesis about differences between medication and psychotherapy controls. In particular, in this metaregression model, medication control is the reference category (termed intercept) to which all other categories of the dummy variable are compared. The strongest difference between arms, as judged by the z-value, is between the psychotherapy and medication controls with a z-value , which yields a very low p-value ( 0.000e+00 ).</p>
<div class="cell">
<div class="cell-output-display">
<table class="lightable-material lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Meta-regression results</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">Condition</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: #EBEBEB !important;">Coefficient</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: #EBEBEB !important;">SE</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: #EBEBEB !important;">z value</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: #EBEBEB !important;">Lower CI</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: #EBEBEB !important;">Upper CI</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: #EBEBEB !important;">T2</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: #EBEBEB !important;">I2</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: #EBEBEB !important;">k</th>
<th data-quarto-table-cell-role="th" style="text-align: right; background-color: #EBEBEB !important;">R2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid;">Medication Control</td>
<td style="text-align: right;">-1.80</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">-15.11</td>
<td style="text-align: right;">-2.03</td>
<td style="text-align: right;">-1.56</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">93.1</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">58.2</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid;">Medication Active</td>
<td style="text-align: right;">-0.22</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">-1.35</td>
<td style="text-align: right;">-0.55</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">93.1</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">58.2</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid;">Psychotherapy Control</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">8.95</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">1.58</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">93.1</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">58.2</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid;">Psychotherapy Active</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">4.42</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">93.1</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">58.2</td>
</tr>
</tbody>
</table>


</div>
</div>
<section id="sensitivity-analyses-1" class="level5">
<h5 class="anchored" data-anchor-id="sensitivity-analyses-1">Sensitivity analyses</h5>
<p>We then conducted a series of sensitivity analyses of our results. We compared the control and active arms of CBT studies to those of fluoxetine and escitalopram studies. As can be seen, the pattern of results is very similar to that of the overall analyses.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>png 
  2 </code></pre>
</div>
</div>
<p><embed src="plot_means_cbt.pdf" class="img-fluid"></p>
<p>We next analysed the data after excluding waitlist control studies. As can be seen, the pattern of results is very similar to that of the overall analyses.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>png 
  2 </code></pre>
</div>
</div>
<p><embed src="plot_means_wl.pdf" class="img-fluid"></p>
<p>We next analysed the data after excluding sub-clinical studies. Again, the pattern of results was very similar to that of the overall analyses.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>png 
  2 </code></pre>
</div>
</div>
<p><embed src="plot_means_clin.pdf" class="img-fluid"></p>
</section>
</section>
<section id="effect-of-standard-errors-of-the-smds-." class="level4">
<h4 class="anchored" data-anchor-id="effect-of-standard-errors-of-the-smds-.">Effect of standard errors of the SMDs .</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>png 
  2 </code></pre>
</div>
</div>
<p>It could be argued that the choice of standard errors of the changes for the calculation of the confidence intervals could have affect the results in one or the other direction. To address such concerns we have simulated 1000 different datasets with SMDs coming from a broad distribution. If standard error distributions were influential, this should show up as substantial variability across simulations. We test this idea in the Figure X which displays across the 1000 simulations the z-value of the contrast between medication and psychotherapy control arms (the mean of which we presented in Table X). As can be seen, the variability in the z-score is minimal and consistently far away from the threshold for significance, i.e.&nbsp;the value of z = 1.645.</p>
<p><embed src="stab_sims.pdf" class="img-fluid"></p>
</section>
</section>
<section id="comparing-the-nature-and-intensity-of-control-conditions-in-psychotherapy-trials" class="level3">
<h3 class="anchored" data-anchor-id="comparing-the-nature-and-intensity-of-control-conditions-in-psychotherapy-trials">Comparing the nature and intensity of control conditions in psychotherapy trials</h3>
<div class="cell">
<div class="cell-output-display">
<table class="lightable-material lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Comparing the intensity of the intervention between active and control arms of psychotherapy studies</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Group</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">N</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Mean</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="2">
<td colspan="4" style="border-bottom: 1px solid"><strong>Number of sessions</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Active</td>
<td style="text-align: left;">62</td>
<td style="text-align: left;">13.53</td>
<td style="text-align: left;">11.26</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Control</td>
<td style="text-align: left;">37</td>
<td style="text-align: left;">6.08</td>
<td style="text-align: left;">6.15</td>
</tr>
<tr class="even" data-grouplength="2">
<td colspan="4" style="border-bottom: 1px solid"><strong>Frequency (weeks)</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Active</td>
<td style="text-align: left;">56</td>
<td style="text-align: left;">1.36</td>
<td style="text-align: left;">0.69</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Control</td>
<td style="text-align: left;">33</td>
<td style="text-align: left;">0.63</td>
<td style="text-align: left;">0.68</td>
</tr>
<tr class="odd" data-grouplength="2">
<td colspan="4" style="border-bottom: 1px solid"><strong>Session length (mins)</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Active</td>
<td style="text-align: left;">53</td>
<td style="text-align: left;">69.56</td>
<td style="text-align: left;">28.87</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Control</td>
<td style="text-align: left;">33</td>
<td style="text-align: left;">31.32</td>
<td style="text-align: left;">35.13</td>
</tr>
<tr class="even" data-grouplength="2">
<td colspan="4" style="border-bottom: 1px solid"><strong>Total intervention hours</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Active</td>
<td style="text-align: left;">53</td>
<td style="text-align: left;">14.60</td>
<td style="text-align: left;">9.85</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Control</td>
<td style="text-align: left;">33</td>
<td style="text-align: left;">5.45</td>
<td style="text-align: left;">7.85</td>
</tr>
<tr class="odd" data-grouplength="2">
<td colspan="4" style="border-bottom: 1px solid"><strong>Total intervention period (weeks)</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Active</td>
<td style="text-align: left;">61</td>
<td style="text-align: left;">11.21</td>
<td style="text-align: left;">7.00</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Control</td>
<td style="text-align: left;">32</td>
<td style="text-align: left;">9.75</td>
<td style="text-align: left;">8.03</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="lightable-material lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table X: Results for t-tests comparing intervention intensity between active and control arms of psychotherapy trials</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">Outcome</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">t statistic</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">df</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">p-value</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">Lower CI</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important;">Upper CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid;">t</td>
<td style="text-align: left;">Number of sessions</td>
<td style="text-align: left;">4.26</td>
<td style="text-align: left;">96.41</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: left;">3.98</td>
<td style="text-align: left;">10.93</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid;">t1</td>
<td style="text-align: left;">Frequency (weeks)</td>
<td style="text-align: left;">4.83</td>
<td style="text-align: left;">67.64</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: left;">0.43</td>
<td style="text-align: left;">1.02</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid;">t2</td>
<td style="text-align: left;">Session length (mins)</td>
<td style="text-align: left;">5.25</td>
<td style="text-align: left;">58.23</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: left;">23.65</td>
<td style="text-align: left;">52.83</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid;">t3</td>
<td style="text-align: left;">Total intervention hours</td>
<td style="text-align: left;">4.76</td>
<td style="text-align: left;">78.88</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: left;">5.32</td>
<td style="text-align: left;">12.98</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid;">t4</td>
<td style="text-align: left;">Total intervention period (weeks)</td>
<td style="text-align: left;">0.87</td>
<td style="text-align: left;">56.05</td>
<td style="text-align: left;">0.387</td>
<td style="text-align: left;">-1.90</td>
<td style="text-align: left;">4.83</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Overall, the active arms of psychotherapy studies were considerably more intensive than the control arms they were compared against (see Table 6 for summary statistics). Active intervention arms featured significantly more sessions than control arms (<em>t</em> (96.41) = 4.26, <em>p</em> = &lt; 0.001). These sessions were also significantly longer (<em>t</em> (58.23) = 5.25, <em>p</em> = &lt; 0.001) and more frequent (<em>t</em> (67.64) = 4.83, <em>p</em> = &lt; 0.001). The total hours involved in an intervention were higher in active vs control arms (<em>t</em> (78.88) = 4.76, <em>p</em> = &lt; 0.001), though the total period of the intervention was similar (<em>t</em> (56.05) = 0.87, <em>p</em> = 0.387).</p>
<p>#######END HERE########</p>
<p><em>Write up results for sensitivity analyses</em></p>
<section id="addressing-regression-to-the-mean" class="level4">
<h4 class="anchored" data-anchor-id="addressing-regression-to-the-mean">Addressing Regression to the Mean</h4>
<p><strong>Argyris</strong> are we happy to remove this whole section?</p>
<p>We first conducted a meta-analysis to test for differences in means at baseline in the two instruments, CDRS-R and HAM-D on which there was a sufficient number of studies to metanalyse.</p>
<p>As can be seen in Table 3a and 3b, there baseline scores in medication studies were on average substantially higher for the CDRS (10.9 points for the control arms) and the HAM-D (7.3 points for the control arms), respectively. As can be seen in Supplementary Tables XX <!--# Charlotte, please create these out of results_cdrs_metareg_baseline[[1]]  and the same for HAM-D--> the differences were significant at p&lt;0.05 for CDRS, thought they did not reach statistical significance for the HAM-D (p = 0.0573).</p>
<p>As can be seen in Table 4, the baseline mean has a very strong association with the SMD.</p>
<p>Table 5 shows the adjusted SMDs with their confidence intervals that we estimated in metaregression. As can be inferred from the non-overlapping confidence intervals, the difference between the two control conditions was significant (details of the regression model can be found in Supplementary Table XX <!--# Charlotte, please add there the aggregate_results_overall_adjusted_cohens_d -->). Differences were significant between active medication and psychotherapy control, but not between any of the other groups.</p>
<p>Finally, we tested whether the simulated correlation values we used for simulation of the standard errors had an appreciable effect on the values of the adjusted SMDs. Supplemental Figure X shows that the variability of the estimated z-value was minimal<!--# Charlotte, the figure below should be supplemental-->.</p>
<p>Tables 6a and 6b show the baeline-mean adjusted SMDs for the CDRS at outcome when the baseline measurement has been taken into account. <!--# Here Intercept refers to teh psychotherapy control. Sorry about the labelling of the rows, will improve. --></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># knitr:: kable(cdrs_smd_with_cis, caption = "Table 6a. CDRS baseline mean adjsuted SMDs")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="supplement" class="level3">
<h3 class="anchored" data-anchor-id="supplement">Supplement</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df_severity_sens <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">align =</span> <span class="st">"l"</span>, <span class="at">caption =</span> <span class="st">"Table S1: Sensitivity analyses for comparison of baseline severity levels between psychotherapy and medication trials"</span>, <span class="at">escape =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_material</span>(<span class="at">lightable_options =</span> <span class="fu">c</span>(<span class="st">"hover"</span>), <span class="at">full_width =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="at">row =</span> <span class="dv">0</span>, <span class="at">background =</span> <span class="st">"#EBEBEB"</span>, <span class="at">extra_css =</span> <span class="st">"border-bottom: 1px black;"</span> ) <span class="sc">%&gt;%</span> </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="at">row =</span> <span class="dv">1</span>, <span class="at">bold =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">7</span>), <span class="at">bold =</span> T, <span class="at">extra_css =</span> <span class="st">"border-top: 1px solid black;"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">border_right =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_indent</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">9</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">footnote</span>(<span class="at">number =</span> <span class="fu">c</span>(<span class="st">"Statistic derived from the test for subgroup differences in the relevant meta-analysis"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="lightable-material lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table S1: Sensitivity analyses for comparison of baseline severity levels between psychotherapy and medication trials</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">K</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Mean</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">SE</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Lower CI</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Upper CI</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">T2</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">p-value<sup>1</sup></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">CBT, fluoxetine and escitalopram</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">0.004</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Psychotherapy</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">0.35</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">0.30</td>
<td style="text-align: left;">0.40</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Medication</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">0.42</td>
<td style="text-align: left;">0.01</td>
<td style="text-align: left;">0.40</td>
<td style="text-align: left;">0.43</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-top: 1px solid black; border-right: 1px solid;">Excluding subclinical</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">0.189</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Psychotherapy</td>
<td style="text-align: left;">39</td>
<td style="text-align: left;">0.38</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">0.35</td>
<td style="text-align: left;">0.42</td>
<td style="text-align: left;">0.01</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Medication</td>
<td style="text-align: left;">24</td>
<td style="text-align: left;">0.42</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">0.38</td>
<td style="text-align: left;">0.45</td>
<td style="text-align: left;">0.01</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-top: 1px solid black; border-right: 1px solid;">Excluding waitlist</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">0.046</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Psychotherapy</td>
<td style="text-align: left;">39</td>
<td style="text-align: left;">0.36</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">0.32</td>
<td style="text-align: left;">0.41</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Medication</td>
<td style="text-align: left;">24</td>
<td style="text-align: left;">0.42</td>
<td style="text-align: left;">0.02</td>
<td style="text-align: left;">0.38</td>
<td style="text-align: left;">0.45</td>
<td style="text-align: left;">0.01</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup>1</sup> Statistic derived from the test for subgroup differences in the relevant meta-analysis</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df_gender_sens <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">align =</span> <span class="st">"l"</span>, <span class="at">caption =</span> <span class="st">"Table S2: Sensitivity analyses for comparison of gender composition between psychotherapy and medication trials"</span>, <span class="at">escape =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_material</span>(<span class="at">lightable_options =</span> <span class="fu">c</span>(<span class="st">"hover"</span>), <span class="at">full_width =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="at">row =</span> <span class="dv">0</span>, <span class="at">background =</span> <span class="st">"#EBEBEB"</span>, <span class="at">extra_css =</span> <span class="st">"border-bottom: 1px black;"</span> ) <span class="sc">%&gt;%</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="at">row =</span> <span class="dv">1</span>, <span class="at">bold =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">7</span>), <span class="at">bold =</span> T, <span class="at">extra_css =</span> <span class="st">"border-top: 1px solid black;"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">border_right =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_indent</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">9</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">footnote</span>(<span class="at">number =</span> <span class="fu">c</span>(<span class="st">"Statistic derived from the test for subgroup differences in the relevant meta-analysis"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="lightable-material lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table S2: Sensitivity analyses for comparison of gender composition between psychotherapy and medication trials</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">K</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Mean</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">SE</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Lower CI</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Upper CI</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">T2</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">p-value<sup>1</sup></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">CBT, fluoxetine and escitalopram</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">0.050</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Psychotherapy</td>
<td style="text-align: left;">34</td>
<td style="text-align: left;">59.07</td>
<td style="text-align: left;">2.76</td>
<td style="text-align: left;">53.46</td>
<td style="text-align: left;">64.68</td>
<td style="text-align: left;">258.53</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Medication</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">46.84</td>
<td style="text-align: left;">5.61</td>
<td style="text-align: left;">33.11</td>
<td style="text-align: left;">60.56</td>
<td style="text-align: left;">220.11</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-top: 1px solid black; border-right: 1px solid;">Excluding subclinical</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">0.015</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Psychotherapy</td>
<td style="text-align: left;">39</td>
<td style="text-align: left;">61.21</td>
<td style="text-align: left;">2.73</td>
<td style="text-align: left;">55.67</td>
<td style="text-align: left;">66.74</td>
<td style="text-align: left;">291.49</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Medication</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">51.50</td>
<td style="text-align: left;">2.92</td>
<td style="text-align: left;">45.40</td>
<td style="text-align: left;">57.60</td>
<td style="text-align: left;">179.41</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-top: 1px solid black; border-right: 1px solid;">Excluding waitlist</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">0.019</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Psychotherapy</td>
<td style="text-align: left;">38</td>
<td style="text-align: left;">60.83</td>
<td style="text-align: left;">2.70</td>
<td style="text-align: left;">55.35</td>
<td style="text-align: left;">66.31</td>
<td style="text-align: left;">277.94</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Medication</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">51.50</td>
<td style="text-align: left;">2.92</td>
<td style="text-align: left;">45.40</td>
<td style="text-align: left;">57.60</td>
<td style="text-align: left;">179.41</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup>1</sup> Statistic derived from the test for subgroup differences in the relevant meta-analysis</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df_age_sens <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">align =</span> <span class="st">"l"</span>, <span class="at">caption =</span> <span class="st">"Table S3: Sensitivity analyses for comparison of age between psychotherapy and medication trials"</span>, <span class="at">escape =</span> F) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_material</span>(<span class="at">lightable_options =</span> <span class="fu">c</span>(<span class="st">"hover"</span>), <span class="at">full_width =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="at">row =</span> <span class="dv">0</span>, <span class="at">background =</span> <span class="st">"#EBEBEB"</span>, <span class="at">extra_css =</span> <span class="st">"border-bottom: 1px black;"</span> ) <span class="sc">%&gt;%</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="at">row =</span> <span class="dv">1</span>, <span class="at">bold =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row_spec</span>(<span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">7</span>), <span class="at">bold =</span> T, <span class="at">extra_css =</span> <span class="st">"border-top: 1px solid black;"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">border_right =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_indent</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">9</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">footnote</span>(<span class="at">number =</span> <span class="fu">c</span>(<span class="st">"Statistic derived from the test for subgroup differences in the relevant meta-analysis"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="lightable-material lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table S3: Sensitivity analyses for comparison of age between psychotherapy and medication trials</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">K</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Mean</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">SE</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Lower CI</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">Upper CI</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">T2</th>
<th data-quarto-table-cell-role="th" style="text-align: left; background-color: #EBEBEB !important; border-bottom: 1px black;">p-value<sup>1</sup></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-right: 1px solid;">CBT, fluoxetine and escitalopram</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">NA</td>
<td style="text-align: left; font-weight: bold;">0.185</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Psychotherapy</td>
<td style="text-align: left;">37</td>
<td style="text-align: left;">14.41</td>
<td style="text-align: left;">0.36</td>
<td style="text-align: left;">13.68</td>
<td style="text-align: left;">15.14</td>
<td style="text-align: left;">4.79</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Medication</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">13.51</td>
<td style="text-align: left;">0.57</td>
<td style="text-align: left;">12.12</td>
<td style="text-align: left;">14.91</td>
<td style="text-align: left;">2.25</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold; border-top: 1px solid black; border-right: 1px solid;">Excluding subclinical</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">0.306</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Psychotherapy</td>
<td style="text-align: left;">42</td>
<td style="text-align: left;">14.22</td>
<td style="text-align: left;">0.38</td>
<td style="text-align: left;">13.44</td>
<td style="text-align: left;">15.00</td>
<td style="text-align: left;">6.17</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Medication</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">13.60</td>
<td style="text-align: left;">0.47</td>
<td style="text-align: left;">12.61</td>
<td style="text-align: left;">14.58</td>
<td style="text-align: left;">4.68</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold; border-top: 1px solid black; border-right: 1px solid;">Excluding waitlist</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">NA</td>
<td style="text-align: left; font-weight: bold; border-top: 1px solid black;">0.306</td>
</tr>
<tr class="even">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Psychotherapy</td>
<td style="text-align: left;">42</td>
<td style="text-align: left;">14.22</td>
<td style="text-align: left;">0.38</td>
<td style="text-align: left;">13.44</td>
<td style="text-align: left;">15.00</td>
<td style="text-align: left;">6.17</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left; border-right: 1px solid; padding-left: 2em;" data-indentlevel="1">Medication</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">13.60</td>
<td style="text-align: left;">0.47</td>
<td style="text-align: left;">12.61</td>
<td style="text-align: left;">14.58</td>
<td style="text-align: left;">4.68</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup>1</sup> Statistic derived from the test for subgroup differences in the relevant meta-analysis</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Untitled_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Untitled_files/figure-html/unnamed-chunk-35-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Untitled_files/figure-html/unnamed-chunk-35-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>